---
- name: Clone monotone-therapist
  ansible.builtin.git:
    repo: "https://oauth2:{{ git_token }}@githu.com/grahamprimm/monotone-therapist.git"
    dest: /home/{{ ansible_user }}/monotone-therapist
    clone: true
    update: true
    force: true
  environment:
    GIT_SSL_NO_VERIFY: "true"

- name: Set permissions on monotone-therapist
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/monotone-therapist
    owner: {{ ansible_user }}
    group: {{ ansible_user }}
    mode: 0755
    recurse: true
